module.exports = {
    "feelings1": [
        { "id": "1", "name": "Angry" },
        { "id": "2", "name": "Sad" },
        { "id": "3", "name": "Disgusted" },
        { "id": "4", "name": "Fearful" },
        { "id": "5", "name": "Bad" },
        { "id": "6", "name": "Surprised" },
        { "id": "7", "name": "Happy" },
    ],
    "feelings2": [
        { "id": "1", "name": "Let Down", "level1Id": "1" },
        { "id": "2", "name": "Humiliated", "level1Id": "1" },
        { "id": "3", "name": "Bitter", "level1Id": "1" },
        { "id": "4", "name": "Mad", "level1Id": "1" },
        { "id": "5", "name": "Aggressive", "level1Id": "1" },
        { "id": "6", "name": "Frustrated", "level1Id": "1" },
        { "id": "7", "name": "Distant", "level1Id": "1" },
        { "id": "8", "name": "Critical", "level1Id": "1" },
        { "id": "9", "name": "", "level1Id": "" },
        { "id": "10", "name": "", "level1Id": "" },
        { "id": "11", "name": "", "level1Id": "" },
        { "id": "12", "name": "", "level1Id": "" },
        { "id": "13", "name": "", "level1Id": "" },
        { "id": "14", "name": "", "level1Id": "" },
        { "id": "15", "name": "", "level1Id": "" },
        { "id": "16", "name": "", "level1Id": "" },
        { "id": "17", "name": "", "level1Id": "" },
        { "id": "18", "name": "", "level1Id": "" },
        { "id": "19", "name": "", "level1Id": "" },
        { "id": "20", "name": "", "level1Id": "" },
        { "id": "21", "name": "", "level1Id": "" },
        { "id": "22", "name": "", "level1Id": "" },
        { "id": "23", "name": "", "level1Id": "" },
        { "id": "24", "name": "", "level1Id": "" },
        { "id": "25", "name": "", "level1Id": "" },
        { "id": "26", "name": "", "level1Id": "" },
        { "id": "27", "name": "", "level1Id": "" },
        { "id": "28", "name": "", "level1Id": "" },
        { "id": "29", "name": "", "level1Id": "" },
        { "id": "30", "name": "", "level1Id": "" },
        { "id": "31", "name": "", "level1Id": "" },
        { "id": "32", "name": "", "level1Id": "" },
        { "id": "33", "name": "", "level1Id": "" },
        { "id": "34", "name": "", "level1Id": "" },
        { "id": "35", "name": "", "level1Id": "" },
        { "id": "36", "name": "", "level1Id": "" },
        { "id": "37", "name": "", "level1Id": "" },
        { "id": "38", "name": "", "level1Id": "" },
        { "id": "39", "name": "", "level1Id": "" },
        { "id": "40", "name": "", "level1Id": "" },
        { "id": "41", "name": "", "level1Id": "" },
    ],
    "feelings3": [
        { "id": "1", "name": "Betrayed", "level2Id": "1" },
        { "id": "2", "name": "Resentful", "level2Id": "1" },
        { "id": "3", "name": "Disrespected", "level2Id": "2" },
        { "id": "4", "name": "Ridiculed", "level2Id": "2" },
        { "id": "5", "name": "Indignant", "level2Id": "3" },
        { "id": "6", "name": "Violated", "level2Id": "3" },
        { "id": "7", "name": "Furious", "level2Id": "4" },
        { "id": "8", "name": "Jealous", "level2Id": "4" },
        { "id": "9", "name": "Provoked", "level2Id": "5" },
        { "id": "10", "name": "Hostile", "level2Id": "5" },
        { "id": "11", "name": "Infuriated", "level2Id": "6" },
        { "id": "12", "name": "Annoyed", "level2Id": "6" },
        { "id": "13", "name": "Withdrawn", "level2Id": "7" },
        { "id": "14", "name": "Numb", "level2Id": "7" },
        { "id": "15", "name": "Skeptical", "level2Id": "8" },
        { "id": "16", "name": "Dismissive", "level2Id": "8" },
    ]
}